# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Auto release

on:
  push:
    tags:
      - "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
        with:
          name: electricgoat/ba-data
          path: ba-data
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.3.1
          poetry install
      - name: Razoring
        run: |
          pwd
          ls -al
          ls ../
      - uses: "softprops/action-gh-release@v1"
        with:
          files: |
            LICENSE.txt
            output/*
